<% PASSWORD_FILE = File.join(RAILS_ROOT, '..', '..', 'shared', 'config', 'dbpassword') %>

development:
  adapter: mysql
  database: wham_development
  username: wham
  password: 9fj388frod92d8j
  host: wham-database
  encoding: utf8
  
test: &TEST
  adapter: mysql
  database: wham_ror_test
  username: wham
  password: 9fj388frod92d8j
  host: wham-database
  encoding: utf8
  
staging:
  adapter: mysql
  database: wham_staging
  username: wham_staging
  # password: 9DlMCtsn3ZWRGA
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: wham-database
  encoding: utf8
  #socket: /var/lib/mysql/mysql.sock
  
production:
  adapter: mysql
  database: wham_production
  username: wham_production
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: wham-database
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock

cucumber:
  <<: *TEST
